// <auto-generated />
using System;
using InvestmentTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentTracker.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUsers_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ApplicationUsers_IsActive");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUsers_Username");

                    b.ToTable("ApplicationUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@investmenttracker.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$vJYHhJvvQPl3/PxKGzHFW.hnJ8X8k8xF.8p0F8M/Z3h6ZrJM8Qq1y",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.InvestmentCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InterestType")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TotalExpectedProfit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_InvestmentCycles_EndDate");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_InvestmentCycles_ParticipantId");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_InvestmentCycles_StartDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InvestmentCycles_Status");

                    b.HasIndex("ParticipantId", "Status")
                        .HasDatabaseName("IX_InvestmentCycles_ParticipantId_Status");

                    b.ToTable("InvestmentCycles", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Participants_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Participants_IsActive");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Participants_NationalId")
                        .HasFilter("\"NationalId\" IS NOT NULL");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Participants_Phone");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvestmentCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentScheduleId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentCycleId")
                        .HasDatabaseName("IX_Payments_InvestmentCycleId");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("IX_Payments_PaymentDate");

                    b.HasIndex("PaymentScheduleId")
                        .HasDatabaseName("IX_Payments_PaymentScheduleId");

                    b.HasIndex("ReferenceNumber")
                        .HasDatabaseName("IX_Payments_ReferenceNumber");

                    b.HasIndex("InvestmentCycleId", "PaymentDate")
                        .HasDatabaseName("IX_Payments_InvestmentCycleId_PaymentDate");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvestmentCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScheduledAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("InvestmentCycleId")
                        .HasDatabaseName("IX_PaymentSchedules_InvestmentCycleId");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_PaymentSchedules_ScheduledDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PaymentSchedules_Status");

                    b.HasIndex("InvestmentCycleId", "ScheduledDate")
                        .HasDatabaseName("IX_PaymentSchedules_InvestmentCycleId_ScheduledDate");

                    b.ToTable("PaymentSchedules", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("string");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Settings_Category");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Settings_Key");

                    b.HasIndex("Category", "DisplayOrder")
                        .HasDatabaseName("IX_Settings_Category_DisplayOrder");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            Description = "Company or application name",
                            DisplayOrder = 1,
                            IsVisible = true,
                            Key = "CompanyName",
                            Value = "Investment Tracker"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            Description = "Default currency code",
                            DisplayOrder = 2,
                            IsVisible = true,
                            Key = "Currency",
                            Value = "USD"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            Description = "Currency symbol for display",
                            DisplayOrder = 3,
                            IsVisible = true,
                            Key = "CurrencySymbol",
                            Value = "$"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Investment",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "decimal",
                            Description = "Default monthly interest rate percentage",
                            DisplayOrder = 1,
                            IsVisible = true,
                            Key = "DefaultInterestRate",
                            Value = "5.0"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Investment",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "int",
                            Description = "Default investment duration in months",
                            DisplayOrder = 2,
                            IsVisible = true,
                            Key = "DefaultDurationMonths",
                            Value = "12"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Notifications",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "bool",
                            Description = "Enable email notifications for payments",
                            DisplayOrder = 1,
                            IsVisible = true,
                            Key = "EnableEmailNotifications",
                            Value = "false"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Reports",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            Description = "Path to logo image for reports",
                            DisplayOrder = 1,
                            IsVisible = true,
                            Key = "ReportLogoPath",
                            Value = "/images/logo.png"
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = "string",
                            Description = "Default date format for display",
                            DisplayOrder = 4,
                            IsVisible = true,
                            Key = "DateFormat",
                            Value = "dd/MM/yyyy"
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.InvestmentCycle", b =>
                {
                    b.HasOne("InvestmentTracker.Core.Entities.Participant", "Participant")
                        .WithMany("InvestmentCycles")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.Payment", b =>
                {
                    b.HasOne("InvestmentTracker.Core.Entities.InvestmentCycle", "InvestmentCycle")
                        .WithMany("Payments")
                        .HasForeignKey("InvestmentCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Core.Entities.PaymentSchedule", "PaymentSchedule")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InvestmentCycle");

                    b.Navigation("PaymentSchedule");
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.PaymentSchedule", b =>
                {
                    b.HasOne("InvestmentTracker.Core.Entities.InvestmentCycle", "InvestmentCycle")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("InvestmentCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentCycle");
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.InvestmentCycle", b =>
                {
                    b.Navigation("PaymentSchedules");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.Participant", b =>
                {
                    b.Navigation("InvestmentCycles");
                });

            modelBuilder.Entity("InvestmentTracker.Core.Entities.PaymentSchedule", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
